name: Deploy Flask App to EC2

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Login to docker hub
        working-directory: ./ai/ai-server/
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Build docker img
        working-directory: ./ai/ai-server/
        run: docker build . -t sarveshgaurishankarsawant/careercraftai:aiserver
      - name: Publish image to docker hub
        working-directory: ./ai/ai-server/
        run: docker push sarveshgaurishankarsawant/careercraftai:aiserver
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull Image from docker hub
        run: docker pull sarveshgaurishankarsawant/careercraftai:aiserver
      - name: Delete old container
        run: docker rm -f swe-careercraftai-aiserver-container
      - name: Run docker container
        run: docker run -d -p 8081:5000 --name swe-careercraftai-aiserver-container sarveshgaurishankarsawant/careercraftai:aiserver