name: Build and Deploy React App to CloudFront
on:
  push:
    branches: [ deploy-frontend-app ]
jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    env:
      BUCKET: careercraftai.sarveshsawant.com
      DIST: dist
      REGION: us-east-2
      DIST_ID: E24P3AF72J814E

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.REGION }}

    - name: Build Static Website
      working-directory: ./frontend/
      run: npm install | npm run build

    - name: Copy files to the production website with the AWS CLI
      working-directory: ./frontend/
      run: |
        aws s3 sync --delete ${{ env.DIST }} s3://${{ env.BUCKET }}

    - name: Copy files to the production website with the AWS CLI
      working-directory: ./frontend/
      run: |
        aws cloudfront create-invalidation \
          --distribution-id ${{ env.DIST_ID }} \
          --paths "/*"