name: Git Workflows

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Java-Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Connect to PostgreSQL
        uses: harmon758/postgresql-action@v1
        with:
          postgresql db: 'postgres'
          postgresql user: 'postgres'
          postgresql password: 'test@123'
      - name: Build with Maven
        working-directory: backend
        run: mvn clean install
      - name: Running test cases
        working-directory: demo
        run: mvn test -Dtest=HealthCheckControllerTest